[book]
src = "src"
title = "The Project Unnamed Book"
authors = ["Project Unnamed contributors"]
language = "en"

[build]
build-dir = "out"

[output.html]
git-repository-url = "https://github.com/prjunnamed/prjunnamed"
